### PR TITLE
using TLS for microstask

### PR DESCRIPTION
**Pull request by rgildein**
- using TLS for microstack as cloud, it could not be disabled [1]

---
[1]: https://discourse.charmhub.io/t/microstack-ussuri-242-can-we-disable-tls/5405

### CODE REVIEW

**Comment by r-f-g** [comment]
> i've never deployed a microstack cloud before. I'm not sure who to touch base with on this PR

@addyess  [here](https://github.com/r-f-g/charm-openstack-integrator/runs/6420513924?check_suite_focus=true) you can see an example of how it works. The functional tests are not working, but environment is successfully created.

**Review by addyess — APPROVED** [review]
okay, i'm +1

**Comment by addyess** [comment]
@neoaggelos do you see anything here?

**Comment by addyess** [comment]
@rgildein Would you still like this merged?  Seems like it is pretty out of date but maybe it'd still be useful somewhere?

**Comment by rgildein** [comment]
> @rgildein Would you still like this merged? Seems like it is pretty out of date but maybe it'd still be useful somewhere?

Hi, yes and in the end we used Charmed OpenStack instead. I'll take a look at this later and let you know.

**Comment by rgildein** [comment]
This is not needed anymore and I think it would be better to wait for Sunbeam.

**Pull request closed without merging**
