### PR TITLE
Add juju-crashdump functionality

### PR DESCRIPTION
**Pull request by r-f-g**
- install juju-crashdump
- upload any juju-crashdumps to GitHub artifact

This feature depends on these [changes](https://github.com/charmed-kubernetes/pytest-operator/pull/48) in pytest-operator and [here](https://github.com/r-f-g/charm-crashdump-test/actions/runs/1831764750) is an example of how it works together.

### CODE REVIEW

**Comment by addyess** [comment]
@r-f-g nothing it jumping out here as scary.  I checked on the @actions/glob and @actions/artifact NPMs and they seem reasoned.  I'm curious as to why the tests are failing though.

**Review by neoaggelos — APPROVED** [review]
MicroStack CI [seems to be failing for quite some time](https://github.com/charmed-kubernetes/actions-operator/runs/4819754420?check_suite_focus=true), so I don't think it is related to this PR. Changes LGTM as well (did not test the glob rule itself, but I don't think it would cause issues).

I'd ask @addyess for an extra approval before merging. @r-f-g is there an example CI run where this is tested already?

**Comment by r-f-g** [comment]
> @r-f-g nothing it jumping out here as scary. I checked on the @actions/glob and @actions/artifact NPMs and they seem reasoned. I'm curious as to why the tests are failing though.

The test on vSphere failing due missing credentials. It's ok, because any of my PR should not have access to credentials. 
The test on microstack failing due this [issue](https://github.com/charmed-kubernetes/github-runner-operator/issues/13).

**Comment by addyess** [comment]
Watch checks run [here](https://github.com/charmed-kubernetes/actions-operator/actions/runs/1894251766)

**Comment by r-f-g** [comment]
> I'd ask @addyess for an extra approval before merging. @r-f-g is there an example CI run where this is tested already?

Yes, I created this [charm](https://github.com/r-f-g/charm-crashdump-test) and you can look at actions runs, e.g. [this](https://github.com/r-f-g/charm-crashdump-test/actions/runs/1831764750).

**Pull request merged**
