### PR TITLE
Use coredns charm rather than minio

### PR DESCRIPTION
**Pull request by addyess**
### Overview

ch:minio latest/stable charm was removed from Charmhub, so let's replace it with one that likely won't be removed for a while.

### CODE REVIEW

**Review by ca-scribner — APPROVED** [review]
minio was removed from charmhub?? this is news to me!

**Comment by addyess** [comment]
> minio was removed from charmhub?? this is news to me!

Latest/stable is no longer there. This is new in the last few weeks. It was there earlier

**Comment by addyess** [comment]
Hmmm. Don't merge until I sort out the test failures. It seems coredns is waiting for something before being active/idle

**Comment by ca-scribner** [comment]
fun fact, this works:

```
juju deploy minio
Deployed "minio" from charm-hub charm "minio", revision 380 in channel ckf-1.9/stable on ubuntu@20.04/stable
```

This breakage coincided with when minio's default channel was changed from `latest` to `ckf-1.9`, which suggests that pylibjuju's `deploy(channel=None)` defaults to `latest` rather than the charm's default channel

**Comment by addyess** [comment]
@ca-scribner pylibjuju strikes again

**Pull request merged**
